---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
    - import_role: name=nginx
    - name: index file
      copy:
        dest: /srv/mattnichols/index.html
        content: |
          Hello, world! Here is a website